ports:
  - port: 8080
tasks:
  - init: echo CREATE DATABASE epidemiweb > start.sql
    command: psql < start.sql 
    command: psql -d epidemiweb < DDL.sql 
    command: rm start.sql
image: gitpod/workspace-postgres  
